### ISSUE TITLE
Proposiciones lógicas mates 

### ISSUE THREAD

**Issue by 23620030** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-23620030#1]
[logica propocicional1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-23620030/files/13191442/logica.propocicional1.pdf)

**Comment by bibiana-m** [comment]
Portadas: 25%
Procedimientos: 25%
Figuras e ilustraciones: 25%
Resultado y conclusiones: 25%

Calificación: 100% / 10 * 20 = 20

Comentario: Excelente.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
